import Head from 'next/head';

interface IPageHead {
  title?: string;
  description?: string;
}

const PageHead = (props: IPageHead) => {
  return (
    <Head>
      <title>{props.title ?? 'Gimetix'}</title>
      <meta
        name="description"
        content={props.description ?? 'Generated by create next app'}
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageHead;
